/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package application;

import api.map.GameMap;

public class App {

    public static void main(String[] args) {
        GameMap map = new GameMap("Zé da manga");

        map.generateRandomMap(15, false, 0.95);
        map.exportMap("C:\\Users\\hugui\\Desktop\\"+map.getMapName()+".txt");
        // map.importMap("C:\\Users\\hugui\\Desktop\\testeImport.txt");

    }
}
